### ISSUE TITLE
function redeclaration error

### ISSUE THREAD

**Issue by krzyko** [OOPS-ORG-PHP/ereg-extension-wrapper#1]
Including (or requiring, also with "_once" suffix) this compatibility wrapper on PHP < 7.0.0 gives me error:
`PHP Fatal error:  Cannot redeclare ereg() in [...]ereg-wrapper.php on line 32`

It looks like that return statement at the beginning of the file (convenient while switching back and forth php versions) doesn't do its job. The cause is described here: [http://php.net/manual/en/function.return.php#112515](url)

The solution which worked for me was to wrap each function in the
`if (!function_exists("wrapped_function_name")) { [...] }` code block to avoid redeclarations.

**Comment by Joungkyun** [comment]
I knew this problem after writing the code, but I thought it would only be used in PHP 7 and later versions, so I left it untouched.

And, considering the problem you are experiencing, it seems more efficient to use **_function_exists_** than **_version_compare_**.

**Comment by krzyko** [comment]
Having code which works on PHP5 and PHP7 simultaneously is useful while doing pre/post migration tests. Many thanks for this new release.
